default: &default
  adapter: postgresql
  host: localhost
  username: excavator
  password: 1
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: qna_dev

test:
  <<: *default
  database: qna_test
